### ISSUE TITLE
utf7 not working

### ISSUE THREAD

**Issue by eahutchins** [3rd-Eden/licenses#6]
I'm seeing:

```
utf7@1.0.0                                       : [object Object]
```

(should be BSD according to the package.json)

**Comment by eahutchins** [comment]
Just figured out it's an extra : in the package.json:

```
  "licenses": [
    {
      "type:": "BSD"
    }
  ],
```

**Comment by 3rd-Eden** [comment]
@eahutchins But it's an easy fix. We should be more flexible for typo's as we're all human after all.

**Comment by 3rd-Eden** [comment]
This was fixed in https://github.com/3rd-Eden/licenses/commit/7cd5df091e674a4e8a7677c28e34a0b2207b13ff
